(function(g){var window=this;var kEa=function(a,b){a.oa("onAutonavCoundownStarted",b)},S4=function(a,b,c){var d=b.Ba();
g.I(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Lc(c?c:"mqdefault.jpg");var f=b instanceof g.WB&&b.lengthSeconds?g.OM(b.lengthSeconds):null,h=!!e;e=h&&"RD"===(new g.WC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.WB?b.wa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.nm||g.NM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.ji(),is_live:l,is_list:h,is_mix:e,background:c?"background-image: url("+
c+")":""};b instanceof g.XC&&(d.playlist_length=b.getLength());a.update(d)},T4=function(a,b){g.U.call(this,{D:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},V4=function(a){g.U.call(this,{D:"div",
W:["ytp-upnext","ytp-player-content"],P:{"aria-label":"{{aria_label}}"},K:[{D:"div",J:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{D:"span",J:"ytp-upnext-top",K:[{D:"span",J:"ytp-upnext-header",V:"Up Next"},{D:"span",J:"ytp-upnext-title",V:"{{title}}"},{D:"span",J:"ytp-upnext-author",V:"{{author}}"}]},{D:"a",J:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
J:"ytp-svg-autoplay-circle",P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",J:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",J:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",J:"ytp-upnext-bottom",K:[{D:"span",J:"ytp-upnext-cancel"},{D:"span",J:"ytp-upnext-paused",V:"Autoplay is paused"}]}]});
this.api=a;this.cancelButton=null;this.C=this.ca("ytp-svg-autoplay-ring");this.u=this.notification=this.o=this.suggestion=null;this.A=new g.F(this.np,5E3,this);this.B=0;var b=this.ca("ytp-upnext-cancel");this.cancelButton=new g.U({D:"button",W:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancel autoplay"},V:"Cancel"});g.A(this,this.cancelButton);this.cancelButton.ma("click",this.pJ,this);this.cancelButton.ba(b);g.A(this,this.A);g.BO(this.api,this.element,this,18788);b=this.ca("ytp-upnext-autoplay-icon");
this.L(b,"click",this.gM);this.FB();this.L(a,"autonavvisibility",this.FB);this.L(a,"mdxnowautoplaying",this.DL);this.L(a,"mdxautoplaycanceled",this.EL);this.L(a,"mdxautoplayupnext",this.aE);U4(this)&&(a=(a=g.jO(g.dO(this.api)))?a.xG():null)&&this.aE(a);g.I(this.element,"ytp-upnext-mobile",this.api.O().o)},X4=function(a,b){a.o||(g.op("a11y-announce","Up Next "+a.suggestion.title),a.B=(0,g.M)(),a.o=new g.F(function(){W4(a,b)},25),W4(a,b),kEa(a.api,b||g.O(a.api.O().experiments,"autoplay_time")||1E4));
g.eo(a.element,"ytp-upnext-autoplay-paused")},U4=function(a){return 3===a.api.getPresentingPlayerType()},W4=function(a,b){var c=b||g.O(a.api.O().experiments,"autoplay_time")||1E4,d=Math.min(lEa(a),c);
c=Math.min(d/c,1);a.C.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&!U4(a)?a.select(!0):a.o&&a.o.start()},lEa=function(a){return(0,g.M)()-a.B},Z4=function(a){Y4(a);
a.B=(0,g.M)();W4(a);g.G(a.element,"ytp-upnext-autoplay-paused")},Y4=function(a){a.o&&(a.o.dispose(),a.o=null)},mEa=function(a){T4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.o=new g.U({D:"div",J:"ytp-subscribe-card",K:[{D:"img",J:"ytp-author-image",P:{src:b.Ld}},{D:"div",J:"ytp-subscribe-card-right",K:[{D:"div",J:"ytp-author-name",V:b.author},{D:"div",J:"html5-subscribe-button-container"}]}]});g.A(this,this.o);this.o.ba(this.element);this.subscribeButton=new g.qQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.We,b.subscribed,"trailer-endscreen",null,null,a);g.A(this,this.subscribeButton);this.subscribeButton.ba(this.o.ca("html5-subscribe-button-container"));
this.hide()},$4=function(a){var b=a.O(),c=g.wx||g.Rh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.U.call(this,{D:"a",W:e,P:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",J:"ytp-videowall-still-image",P:{style:"{{background}}"}},{D:"span",J:"ytp-videowall-still-info",K:[{D:"span",J:"ytp-videowall-still-info-bg",K:[{D:"span",J:"ytp-videowall-still-info-content",P:c,K:[{D:"span",J:"ytp-videowall-still-info-title",V:"{{title}}"},{D:"span",J:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{D:"span",J:"ytp-videowall-still-info-live",V:"Live"},{D:"span",J:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{D:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",J:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",J:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",V:"{{playlist_length}}"},")"]}]},{D:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",J:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",J:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.o=new g.Is(this);g.A(this,this.o);this.ma("click",this.onClick);this.ma("keypress",this.A);this.o.L(a,"videodatachange",this.Na);g.CO(a,this.element,this);this.Na()},a5=function(a){T4.call(this,a,"videowall-endscreen");
var b=this;this.H=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.I=!1;this.G=null;this.u=new g.vQ(this);g.A(this,this.u);this.F=new g.F(function(){g.G(b.element,"ytp-show-tiles")},0);
g.A(this,this.F);var c=new g.U({D:"button",W:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Previous"},K:[g.nN()]});g.A(this,c);c.ba(this.element);c.ma("click",this.rI,this);this.table=new g.XM({D:"div",J:"ytp-endscreen-content"});g.A(this,this.table);this.table.ba(this.element);c=new g.U({D:"button",W:["ytp-button","ytp-endscreen-next"],P:{"aria-label":"Next"},K:[g.oN()]});g.A(this,c);c.ba(this.element);c.ma("click",this.qI,this);this.o=new V4(a);g.A(this,this.o);g.zO(this.player,this.o.element,
4);this.hide()},b5=function(a){return g.AO(a.player)&&a.jy()&&!a.B},nEa=function(a,b){return(0,g.Nc)(b.suggestions,function(c){c=g.QM(a.H.O(),c);
g.A(a,c);return c})},c5=function(a){var b=a.Yu();
b!==a.I&&(a.I=b,a.player.S("autonavvisibility"))},d5=function(a){g.NO.call(this,a);
this.endScreen=null;this.listeners=new g.Is(this);g.A(this,this.listeners);this.o=a.O();oEa(a)?this.endScreen=new a5(this.player):this.o.Wa?this.endScreen=new mEa(this.player):this.endScreen=new T4(this.player);g.A(this,this.endScreen);g.zO(this.player,this.endScreen.element,4);this.lD();this.listeners.L(a,"videodatachange",this.lD,this);this.listeners.L(a,g.Mz("endscreen"),this.nI,this);this.listeners.L(a,"crx_endscreen",this.oI,this)},oEa=function(a){a=a.O();
return a.Fa&&!a.Wa};g.t(T4,g.U);g.k=T4.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.jy=function(){return!1};
g.k.Yu=function(){return!1};
g.k.iA=function(){return!1};g.t(V4,g.U);g.k=V4.prototype;g.k.np=function(){this.notification&&(this.A.stop(),this.rb(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.FB=function(){this.fb(g.eO(this.api));g.FO(this.api,this.element,g.eO(this.api))};
g.k.XL=function(){window.focus();this.np()};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.P(this.api.O().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ba(),this.np(),this.notification=new Notification("Up Next",{body:b.title,icon:b.Lc()}),this.u=this.L(this.notification,"click",this.XL),this.A.start())}Y4(this);this.api.nextVideo(!1,a)};
g.k.gM=function(a){!g.Ke(this.cancelButton.element,g.Ep(a))&&g.qP(a,this.api)&&this.select()};
g.k.pJ=function(){g.gO(this.api,!0)};
g.k.DL=function(a){U4(this);this.show();X4(this,a)};
g.k.aE=function(a){U4(this);this.suggestion&&this.suggestion.Ba().videoId===a.Ba().videoId||(this.suggestion=a,S4(this,a,"hqdefault.jpg"))};
g.k.EL=function(){U4(this);Y4(this);this.hide()};
g.k.X=function(){Y4(this);this.np();g.U.prototype.X.call(this)};g.t(mEa,T4);g.t($4,g.U);$4.prototype.select=function(){var a=this.suggestion.Ba().videoId,b=this.suggestion.getPlaylistId();(g.MT(this.api.app,a,this.suggestion.uc,b,void 0,this.suggestion.ZF||void 0)||this.api.da("web_player_endscreen_double_log_fix_killswitch"))&&g.EO(this.api,this.element)};
$4.prototype.onClick=function(a){g.qP(a,this.api,this.u,this.suggestion.uc||void 0)&&this.select()};
$4.prototype.A=function(a){switch(a.keyCode){case 13:case 32:g.Jp(a)||(this.select(),g.Ip(a))}};
$4.prototype.Na=function(){var a=this.api.getVideoData(),b=this.api.O();this.u=a.dc?!1:b.u};g.t(a5,T4);g.k=a5.prototype;g.k.create=function(){T4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=nEa(this,a),this.videoData=a);this.Hh();this.u.L(this.player,"appresize",this.Hh);this.u.L(this.player,"onVideoAreaChange",this.Hh);this.u.L(this.player,"videodatachange",this.Na);this.u.L(this.player,"autonavchange",this.Zu);this.u.L(this.player,"autonavcancel",this.pI);a=this.videoData.autonavState;a!==this.G&&this.Zu(a);this.u.L(this.element,"transitionend",this.qN)};
g.k.destroy=function(){g.Ks(this.u);g.Ve(this.stills);this.stills=[];this.suggestions=null;T4.prototype.destroy.call(this);g.eo(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.k.jy=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){T4.prototype.show.call(this);g.eo(this.element,"ytp-show-tiles");this.player.O().o?g.Yn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.gO(this.player,!1);b5(this)?(c5(this),2===this.videoData.autonavState?this.player.O().da("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.o.select(!0):X4(this.o):3===this.videoData.autonavState&&Z4(this.o)):(g.gO(this.player,!0),c5(this))};
g.k.hide=function(){T4.prototype.hide.call(this);Z4(this.o);c5(this)};
g.k.qN=function(a){g.Ep(a)===this.element&&this.Hh()};
g.k.Hh=function(){if(this.suggestions&&this.suggestions.length){g.G(this.element,"ytp-endscreen-paginate");var a=this.H.Vk(!0,this.H.isFullscreen()),b=g.$N(this.H);b&&(b=b.Mc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,w=e<=h-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&w)n-=q*m,e+=2;else if(u)n-=
r*m,b+=2;else if(w)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.fi(a,m,n);g.Oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.o;f=this.suggestions[0];c.suggestion=f;S4(c,f,"hqdefault.jpg");g.I(this.element,"ytp-endscreen-takeover",b5(this));c5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(q=c,r=0,d&&f>=b-2&&h>=
e-2?r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),q=g.Yd(q+this.A,l),0!==r){u=this.stills[c];u||(u=new $4(this.player),this.stills[c]=u,a.appendChild(u.element));w=Math.floor(n*h/e);var B=Math.floor(m*f/b),z=Math.floor(n*(h+r)/e)-w-4,E=Math.floor(m*(f+r)/b)-B-4;g.Wh(u.element,B,w);g.fi(u.element,E,z);g.Oh(u.element,"transitionDelay",(h+f)/20+"s");g.I(u.element,"ytp-videowall-still-mini",1===r);g.I(u.element,"ytp-videowall-still-large",2<r);r=u;q=this.suggestions[q];r.suggestion!==q&&(r.suggestion=
q,u=r.api.O(),w=g.bo(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",S4(r,q,w),g.Xy(u)&&(u=q.ji(),u=g.Gd(u,g.FJ({},"emb_rel_end")),r.la("url",u)),(q=(q=q.uc)&&q.itct)&&g.DO(r.api,r.element,q));c++}g.I(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.He(e.element),g.Ue(e);this.stills.length=c}};
g.k.Na=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=nEa(this,a),this.videoData=a,this.Hh())};
g.k.qI=function(){this.A+=this.stills.length;this.Hh()};
g.k.rI=function(){this.A-=this.stills.length;this.Hh()};
g.k.iA=function(){return!!this.o.o};
g.k.Zu=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,Y4(this.o),this.Ma()&&this.Hh()):(this.C=!0,this.Ma()&&b5(this)&&(2===a?X4(this.o):3===a&&Z4(this.o)))};
g.k.pI=function(a){if(a){for(a=0;a<this.stills.length;a++)g.FO(this.H,this.stills[a].element,!0);this.Zu(1)}else this.B=null,this.C=!1;this.Hh()};
g.k.Yu=function(){return this.Ma()&&b5(this)};g.t(d5,g.NO);g.k=d5.prototype;g.k.GA=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!oEa(this.player)||b;var c=a.Ak||g.fz(a.Ga),d=g.NT(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.FA=function(){return this.endScreen.Yu()};
g.k.nH=function(){return this.FA()?this.endScreen.iA():!1};
g.k.X=function(){g.lR(this.player.app,"endscreen",void 0);g.NO.prototype.X.call(this)};
g.k.load=function(){g.NO.prototype.load.call(this);this.endScreen.show()};
g.k.unload=function(){g.NO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.nI=function(a){this.GA()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.oI=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.lD=function(){g.lR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.Jz(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.Jz(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.vO(this.player,[a,b])};g.YO.endscreen=d5;})(_yt_player);
